### ISSUE TITLE
想联系交流一下

### ISSUE THREAD

**Issue by icymars0815** [mxia9416/MACC#1]
大佬方便交流一下这个项目？纯粹是出于个人兴趣，我的邮箱是qiwangumass@gmail.com

**Comment by mxia9416** [comment]
你好，如果是开发相关直接看[MAA官方教程文档](https://github.com/MaaXYZ/MaaFramework/blob/main/docs/zh_cn/1.1-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B.md#%E5%BC%80%E5%8F%91%E6%80%9D%E8%B7%AF)，用里面的项目模板和视频教程学习即可

**Comment by icymars0815** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript 附上链接，而且这个框架是可以直接对MAA进行调度的

**Comment by mxia9416** [comment]
感谢指路，大概看了一下，如果没理解错，alas调度maa实际功能还是maa，优势是引入了alas的任务调度器来实现无缝收菜等，等于是一个高级的maa“启动器”？ 另外官方的maa插件例子给的是明日方舟的maa本体，如果要配合无期迷途版本可能还需要对alas做一些修改（没有深入看）。
因为本人的需求仅仅是每天登录一次游戏收菜，也不追求无缝/无损/无感知/全自动等，所以暂无融入alas的需求。不过如果你想基于alas+maa开发，可随意使用macc或者基于它优化修改，都没有问题。

**Comment by icymars0815** [comment]
对的，严格来说只是兼容，因为我也用alas挂星穹铁道，感觉这套系统比MAA逻辑上更好用。
我在看能不能直接开发alas版本的，但是我属于小白的，实际上可能需要很久，到时候如果真出来demo会跟你说的。
最后表示感谢，因为我找57的项目很久了，本来我自己想手搓的，但是你这里刚好做出来了，我也是收菜党，只是希望工具能变得更好用，感谢开发。
